import 'package:flutter/material.dart';

import '../components/UI/ListWidgetComponent.dart';
import '../components/UI/FloatingActionButtonComp.dart';

class PreHarvestScreen extends StatelessWidget {
  const PreHarvestScreen({Key? key}) : super(key: key);

  static const routeName = '/pre-harvest';

  @override
  Widget build(BuildContext context) {
    final argumentsMap = ModalRoute.of(context)?.settings.arguments as Map;
    final plotName = argumentsMap['argument'];
    return Scaffold(
      appBar: AppBar(
        title: Text('Pre Harvest - Plot $plotName'),
        centerTitle: true,
      ),
      body: ListView(
        children: [
          ListWidgetComponent(
            title: 'Lodging Resistance',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Very High',
              '2-High',
              '3-Moderate',
              '4-Low',
              '5-Very Low',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Husk Cover',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Fully',
              '2-Partially',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Cob Size',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Very Good',
              '2-Good',
              '3-Fair',
              '4-Bad',
              '5-Very Bad',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Number of Cobs per Plant',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Very Good',
              '2-Good',
              '3-Fair',
              '4-Bad',
              '5-Very Bad',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Plant Height',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Very Good',
              '2-Good',
              '3-Fair',
              '4-Bad',
              '5-Very Bad',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Bird Damage',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Slight Damage',
              '2-Light Damage',
              '3-Moderate',
              '4-Heavy',
              '5-Very Heavy',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Panicle Appreciation',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Very Good',
              '2-Good',
              '3-Fair',
              '4-Bad',
              '5-Very Bad',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Grain Quality Appreciation',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Very Good',
              '2-Good',
              '3-Fair',
              '4-Bad',
              '5-Very Bad',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Head Size Appreciation',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Very Good',
              '2-Good',
              '3-Fair',
              '4-Bad',
              '5-Very Bad',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Plant Growth Habit Appreciation',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Very Good',
              '2-Good',
              '3-Fair',
              '4-Bad',
              '5-Very Bad',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Pod Length Appreciation',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Very Good',
              '2-Good',
              '3-Fair',
              '4-Bad',
              '5-Very Bad',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
          ListWidgetComponent(
            title: 'Willingness to Cultivate Next Season',
            subtitle: 'Blank',
            value: 'Blank',
            onChangeDateValueHandler: () {},
            onChangeTextValueHandler: () {},
            onSubmitHandler: () {},
            isDropDownField: true,
            listOfValues: <String>[
              '1-Yes, Very Sure',
              '2-Yes',
              '3-Perhaps, Not Sure',
              '4-No',
              '5-Definitely Not',
            ],
            isTrait: true,
            isTextField: false,
            onChangeGenComValueHandler: () {},
          ),
        ],
      ),
      floatingActionButton: FloatingActionButtonComp(),
    );
  }
}
